// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKKDw7xeei431_1Pv3AJxupdEXe0HA65w',
    appId: '1:1043908794987:web:c68c40fbe33a1b17c5ef2e',
    messagingSenderId: '1043908794987',
    projectId: 'rochajohn-firebase-tasks',
    authDomain: 'rochajohn-firebase-tasks.firebaseapp.com',
    storageBucket: 'rochajohn-firebase-tasks.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEBA-aa6iciJtDteLTW03RYhvTQ9Kr1ew',
    appId: '1:1043908794987:android:28f595bf29a8845dc5ef2e',
    messagingSenderId: '1043908794987',
    projectId: 'rochajohn-firebase-tasks',
    storageBucket: 'rochajohn-firebase-tasks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWdoXKUK1m7uX2Ou1u71VtRtCD6100Jv0',
    appId: '1:1043908794987:ios:7052b1164f35b675c5ef2e',
    messagingSenderId: '1043908794987',
    projectId: 'rochajohn-firebase-tasks',
    storageBucket: 'rochajohn-firebase-tasks.appspot.com',
    iosBundleId: 'com.example.todoListFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWdoXKUK1m7uX2Ou1u71VtRtCD6100Jv0',
    appId: '1:1043908794987:ios:fe24bc4111af8d1bc5ef2e',
    messagingSenderId: '1043908794987',
    projectId: 'rochajohn-firebase-tasks',
    storageBucket: 'rochajohn-firebase-tasks.appspot.com',
    iosBundleId: 'com.example.todoListFirebase.RunnerTests',
  );
}
